before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
    # override $NODE_VERSION
    - CI_COMMIT_MESSAGE="$(git log -1 --pretty=%s)" && if (printf "$CI_COMMIT_MESSAGE" | grep -qE "\bNODE_VERSION="); then nvm install "$(printf "$CI_COMMIT_MESSAGE" | sed -e "s/.*\bNODE_VERSION=//" -e "s/ .*//")" && node --version && npm --version; fi
branches:
    only:
    - /^alpha$/
    - /^beta$/
    - /^benchmark\..*/
    - /^cron$/
    - /^docker\..*/
    - /^master$/
    - /^publish$/
    - /^task$/
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: 1K99UI5LpPwxu9ECa4v3Da4ZH4sk43FxLuZdiQXb1M+M+RJRQtCTWrFKYR4myktSQzCMKiZiwOYk1vZ4I7PZi/kjJ3bg2u21nn4agTbZmHD/KqtAdv2S+oIvz+HNK/H3A9JeRoWLXaNwhyZGD784Bf9DauZQB6UKAmI/DaZrftHZbMLKHssXPBE1Xjvnao40dRK+fy4UMtwPDt2kmzLJ87z8aSSc8GObu4UK9fV87NBy0jyUfbPa1R9hvo2/hAX8lfq2lKGFacLvKVfblYf18irkpH0k6PvdE1ItcxALfLJfs++vxHMF/5FSQw2CJ3+vNMAU4UBcNdLf7HeU6b/zMTP2kl0wU34tOm8T4QnL49NttvG7egQZrzD9HYpnBHhhfiwvf5qJXN2jPOOGSw8rF4pvVPDAtuXwcnykeFnvC9+lX9AGx7xt3HmDi1rY/+e6UJV9axBOjsU1fmC6LPWAW/3LwW9IOfPSZSxWU5PfdUMM4RPL4m0PB2wwDX7DPGh902qEmZ0tFfprs60D5YHD3qa3HbTpURgkP0k4g2E3d+eHay+Xok3sziGf4IOM5IYU9doaMaioZOUnuM8QAhstqtz52LnXMAXFGw/nN+dTkXq29UbaB15/3/exj6MrwXDJbBvdBtg/y1OcvZMFrtHMY7EqU00T+co1+4IZ/tGYOOg= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    # - 8
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
