before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
    # override $NODE_VERSION
    - CI_COMMIT_MESSAGE="$(git log -1 --pretty=%s)" && if (printf "$CI_COMMIT_MESSAGE" | grep -qE "\bNODE_VERSION="); then nvm install "$(printf "$CI_COMMIT_MESSAGE" | sed -e "s/.*\bNODE_VERSION=//" -e "s/ .*//")" && node --version && npm --version; fi
branches:
    only:
    - /^alpha$/
    - /^beta$/
    - /^benchmark\..*/
    - /^cron$/
    - /^docker\..*/
    - /^master$/
    - /^publish$/
    - /^task$/
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: p4kzdTXEubcVVt8yK8z6weuDrVA5qM6Lcp9A4gl1+djoCn2mQRILJR3jvJwPrwElHQkf1xabavx5hRVLgV5APhNvHUm1zanVFxv93212y+oYTgVpaWwubH3U6TW5K5NkFg9Xzu2AlysdshOhsU6Hj6wsHWKBRgNvtc68T1orbqbB2uIK1s53P+SfzA9AXP9UQlJ6NblycuU1koZZlOWmkVslN9aNC2/4HeF1Xyd2ZZFvmKqqsr8hfOWa5u4r/BOTZxNWWQjo60DFj6AMQRbQiPTvFR/8+VrcpYvtVnymZ6WQrcaSypaC0XWI5wQ9lLGN2BjrJ4BiXNIa+XoYsmtqXSZwrhloOz98AD7eJCNBMVSt3iA7ALoe8dURUoFOaXfYtALZ1hxF3m+lsRxnjcDNg2odVPFwWbfqBy4TYYvxb8fo+jwCpW91oGPHlh39/RSowF+f4TpmBp3yFjjdIJRLl78tEuinOox0VpQ0RT9Jy19bUOEsgsehJgMEk5/5MoX61SUQWhKGmzmD2JElQm9EQUl9EwvWx3WTLWDm0G9/v7MPD/7pciE6Bz5aPaczW055qgdPwz3zETIhL7XWOe4i/KJFx8KPRLedsojF35H7Z4dW6U15sWg18AMWNkpZAv3ennjiVJUzLrVa3JMx6jkVq3zRsuu+SyALrnjyJOpvv4o= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    # - 8
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
